import 'server-only';
import crypto from 'node:crypto';
import type { RiskReport } from './agent/prompts';

export function verifySlackSignature(
  headers: Headers,
  rawBody: string
): boolean {
  const secret = process.env.SLACK_SIGNING_SECRET;
  if (!secret) return process.env.MOCK_FALLBACK === 'true';

  const timestamp = headers.get('x-slack-request-timestamp');
  const signature = headers.get('x-slack-signature');
  if (!timestamp || !signature) return false;

  const fiveMinAgo = Math.floor(Date.now() / 1000) - 60 * 5;
  if (Number(timestamp) < fiveMinAgo) return false;

  const base = `v0:${timestamp}:${rawBody}`;
  const expected =
    'v0=' + crypto.createHmac('sha256', secret).update(base).digest('hex');

  try {
    return crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected));
  } catch {
    return false;
  }
}

export async function postMessage(channel: string, blocks: unknown[]) {
  const token = process.env.SLACK_BOT_TOKEN;
  if (!token) {
    if (process.env.MOCK_FALLBACK === 'true') {
      console.log('[slack:mock] postMessage', { channel, blockCount: blocks.length });
      return { ok: true, mocked: true };
    }
    throw new Error('SLACK_BOT_TOKEN missing');
  }

  const res = await fetch('https://slack.com/api/chat.postMessage', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      Authorization: `Bearer ${token}`
    },
    body: JSON.stringify({ channel, blocks })
  });

  return res.json();
}

export function buildRiskReportBlocks(report: RiskReport): unknown[] {
  const verdictEmoji: Record<RiskReport['verdict'], string> = {
    clear: ':large_green_circle:',
    watch: ':large_yellow_circle:',
    high_risk: ':large_orange_circle:',
    critical: ':red_circle:'
  };

  const blocks: unknown[] = [
    {
      type: 'header',
      text: {
        type: 'plain_text',
        text: `${verdictEmoji[report.verdict]} IP-Pulse risk report — ${report.verdict.replace('_', ' ').toUpperCase()}`
      }
    },
    {
      type: 'section',
      fields: [
        {
          type: 'mrkdwn',
          text: `*Confidence*\n${Math.round(report.confidence * 100)}%`
        },
        {
          type: 'mrkdwn',
          text: `*Matched patents*\n${report.matchedPatents.length}`
        },
        {
          type: 'mrkdwn',
          text: `*Prior art hits*\n${report.priorArtFindings.length}`
        },
        {
          type: 'mrkdwn',
          text: `*Holder is NPE*\n${report.litigationProfile.isKnownNPE ? 'YES — caution' : 'No'}`
        }
      ]
    },
    { type: 'divider' },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Roadmap impact*\n${report.roadmapImpact}`
      }
    }
  ];

  for (const m of report.matchedPatents.slice(0, 3)) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*<https://patents.google.com/patent/${m.patentNo}|${m.patentNo}> — ${m.title}*\n_${m.assignee}_ · priority ${m.priorityDate}\n${m.claimSummary}\n> ${m.overlapWithUserStack}`
      }
    });
  }

  if (report.priorArtFindings.length) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text:
          '*Prior art found*\n' +
          report.priorArtFindings
            .slice(0, 3)
            .map(
              (p) =>
                `• <${p.snippetUrl}|${p.repo}> — ${p.firstCommitDate}${p.predatesPriorityDate ? ' :zap: *predates priority*' : ''}`
            )
            .join('\n')
      }
    });
  }

  if (report.recommendedActions.length) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text:
          '*Recommended actions*\n' +
          report.recommendedActions.map((a) => `• ${a}`).join('\n')
      }
    });
  }

  blocks.push({
    type: 'context',
    elements: [
      {
        type: 'mrkdwn',
        text: 'Generated by IP-Pulse · Claude + Kimi K2.6 on Akash · MCP tools via WunderGraph Cosmo'
      }
    ]
  });

  return blocks;
}
