#!/usr/bin/env bash
set -euo pipefail

# Chainguard security scan — generate SBOM with syft + vulnerability report with grype
# against the built IP-Pulse web and worker images.
#
# Outputs (Markdown + JSON) land in ./artifacts/ for attach-to-README + demo.

ARTIFACTS="${PWD}/artifacts"
mkdir -p "$ARTIFACTS"

WEB_IMAGE="${WEB_IMAGE:-ippulse-web:latest}"
WORKER_IMAGE="${WORKER_IMAGE:-ippulse-worker:latest}"

need() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: $1 not installed. Install via: $2" >&2
    exit 1
  fi
}

need syft "brew install syft  |  go install github.com/anchore/syft/cmd/syft@latest"
need grype "brew install grype |  go install github.com/anchore/grype/cmd/grype@latest"

scan_image() {
  local image="$1"
  local tag="${image%%:*}"
  local slug="${tag##*/}"

  echo ""
  echo "=== $image ==="

  echo "→ SBOM..."
  syft "$image" -o spdx-json > "$ARTIFACTS/${slug}-sbom.spdx.json"
  syft "$image" -o table > "$ARTIFACTS/${slug}-sbom.txt"

  echo "→ Vulnerabilities..."
  grype "$image" -o table > "$ARTIFACTS/${slug}-grype.txt" || true
  grype "$image" -o json > "$ARTIFACTS/${slug}-grype.json" || true

  local high_count
  high_count=$(grep -cE "(High|Critical)" "$ARTIFACTS/${slug}-grype.txt" || true)
  echo "→ High/Critical CVEs: ${high_count:-0}"
}

scan_image "$WEB_IMAGE"
scan_image "$WORKER_IMAGE"

cat > "$ARTIFACTS/README.md" <<EOF
# Security scan output

Generated by \`scripts/security-scan.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ).

Targets:

- \`$WEB_IMAGE\`
- \`$WORKER_IMAGE\`

Each target produced:

- \`<image>-sbom.spdx.json\` — software bill of materials (SPDX)
- \`<image>-sbom.txt\` — human-readable package inventory
- \`<image>-grype.txt\` / \`.json\` — vulnerability report

The Chainguard \`cgr.dev/chainguard/node\` base image is distroless and non-root; the expected grype outcome is **0 High, 0 Critical** CVEs. Grep the \`*-grype.txt\` files for "High" / "Critical" to verify.
EOF

echo ""
echo "✓ Artifacts in $ARTIFACTS/"
